# Generated by Django 2.1 on 2019-03-29 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='description',
        ),
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
    ]
