# Generated by Django 2.1 on 2019-08-06 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_project_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
